"""Generated from the Strata IDL — do not edit by hand.

Regenerate with ``python tools/generate.py``. The CI drift guard fails if this
file is stale.
"""

from __future__ import annotations

# Every data-plane command with a generated typed method.
GENERATED_COMMANDS = [
    'admin.config',
    'admin.config_key',
    'admin.describe',
    'admin.health',
    'admin.info',
    'admin.metrics',
    'admin.ping',
    'arrow.export',
    'arrow.import',
    'branch.create',
    'branch.delete',
    'branch.fork',
    'branch.fork_at_timestamp',
    'branch.fork_at_version',
    'branch.get',
    'branch.list',
    'event.append',
    'event.batch_append',
    'event.count',
    'event.exists',
    'event.get',
    'event.list',
    'event.range',
    'event.range_time',
    'event.types',
    'event.verify_chain',
    'graph.analytics.bfs',
    'graph.analytics.cdlp',
    'graph.analytics.lcc',
    'graph.analytics.pagerank',
    'graph.analytics.sssp',
    'graph.analytics.wcc',
    'graph.apply_delete_policy',
    'graph.batch_write',
    'graph.bindings',
    'graph.bulk_insert',
    'graph.create',
    'graph.delete',
    'graph.edge.add',
    'graph.edge.get',
    'graph.edge.remove',
    'graph.list',
    'graph.meta',
    'graph.neighbors',
    'graph.node.add',
    'graph.node.get',
    'graph.node.list',
    'graph.node.remove',
    'graph.nodes_by_type',
    'graph.ontology.define_link_type',
    'graph.ontology.define_object_type',
    'graph.ontology.delete_link_type',
    'graph.ontology.delete_object_type',
    'graph.ontology.freeze',
    'graph.ontology.get',
    'graph.ontology.summary',
    'graph.sample',
    'json.batch_delete',
    'json.batch_exists',
    'json.batch_get',
    'json.batch_set',
    'json.count',
    'json.delete',
    'json.exists',
    'json.get',
    'json.history',
    'json.index.create',
    'json.index.drop',
    'json.index.list',
    'json.list',
    'json.sample',
    'json.scan',
    'json.set',
    'kv.batch_delete',
    'kv.batch_exists',
    'kv.batch_get',
    'kv.batch_put',
    'kv.count',
    'kv.delete',
    'kv.exists',
    'kv.get',
    'kv.history',
    'kv.list',
    'kv.put',
    'kv.sample',
    'kv.scan',
    'space.create',
    'space.delete',
    'space.exists',
    'space.list',
    'vector.batch_delete',
    'vector.batch_exists',
    'vector.batch_get',
    'vector.batch_upsert',
    'vector.collection.create',
    'vector.collection.delete',
    'vector.collection.list',
    'vector.collection.stats',
    'vector.count',
    'vector.delete',
    'vector.delete_all',
    'vector.delete_by_filter',
    'vector.exists',
    'vector.get',
    'vector.history',
    'vector.index.query',
    'vector.keys',
    'vector.metadata.update',
    'vector.query',
    'vector.sample',
    'vector.scan',
    'vector.upsert',
]

# Commands intentionally not surfaced (coverage guard allowlist).
UNCOVERED_REASON = 'out of the V1 data-plane surface (requires the inference/hub executor features)'
UNCOVERED_COMMANDS = [
    'admin.hub_clone',
    'admin.remote',
    'inference.cache_status',
    'inference.capability',
    'inference.detokenize',
    'inference.embed',
    'inference.embed_batch',
    'inference.generate',
    'inference.models.list',
    'inference.models.local',
    'inference.models.pull',
    'inference.rank',
    'inference.tokenize',
    'inference.unload',
]

METHOD_BY_ID = {i: i.replace('.', '_') for i in GENERATED_COMMANDS}
