"""Type stubs for the native binding (`_stratadb`)."""

from typing import Optional

class StrataNativeError(Exception):
    """Raised on a domain failure; carries the error-status JSON as its arg."""

class Handle:
    """One open Strata database, over the executor's serialized command wire."""

    @staticmethod
    def open_durable(
        path: str,
        durability: Optional[str] = ...,
        ipc: Optional[str] = ...,
        memory_budget: Optional[int] = ...,
    ) -> "Handle": ...
    @staticmethod
    def open_cache() -> "Handle": ...
    def execute(self, command_json: str) -> str: ...
    def set_scope(self, branch: Optional[str] = ..., space: Optional[str] = ...) -> None: ...
    def default_branch(self) -> str: ...
    def default_space(self) -> str: ...
    def close(self) -> None: ...

def version() -> str: ...
